### PR TITLE
Refresh after wallet connected and transaction completed

### PR DESCRIPTION
**Pull request by developer-junaid**
Here I've implemented window.location.reload() in the connectWallet() and sendTransaction() function, to refresh the page automatically, whenever the wallet is connected or the transaction is completed.

### CODE REVIEW

**Comment by brlojam4932** [comment]
awesome - i just tried it and it works!

**Comment by adrianhajdin** [comment]
Great, thanks! Due to your linter settings, a lot of the lines have been changed. If you can make a pull request with only the window.reload change, I could merge it in.

**Comment by sabarinathan145** [comment]
Hi adrianhajdin I'm getting error at no ethereum object at
transactionContext.Jsx

I have also posted that issue on our GitHub kindly make a solution for that
, I'm new to learn solidity nd react PL help to clear that error 🙏

**Comment by developer-junaid** [comment]
> Great, thanks! Due to your linter settings, a lot of the lines have been changed. If you can make a pull request with only the window.reload change, I could merge it in.

Removed All linter changes, Now you can merge !

**Pull request merged**
